# Generated by Django 5.1.5 on 2025-03-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lesson_name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='classroom',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
