# Generated by Django 5.1.5 on 2025-03-27 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_lesson_name_alter_user_classroom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_friends', models.IntegerField(choices=[(2, 'Для всех'), (1, 'Только друзья'), (0, 'Только я')], default=2)),
                ('show_grades', models.IntegerField(choices=[(2, 'Для всех'), (1, 'Только друзья'), (0, 'Только я')], default=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
