# Generated by Django 5.1.5 on 2025-03-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='subject',
        ),
        migrations.AddField(
            model_name='grade',
            name='comment',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='lesson',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
