# Generated by Django 5.1.5 on 2025-03-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_grade_teacher_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
