# Generated by Django 5.1.5 on 2025-03-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_alter_grade_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
