# Generated by Django 5.1.5 on 2025-02-16 14:44

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, default='profile_image/default.png', upload_to=blog.models.rename_file),
        ),
    ]
