# Generated by Django 5.1.5 on 2025-02-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('floor', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='map/')),
            ],
        ),
    ]
